# Generated by Django 5.1.4 on 2024-12-25 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the documentation', max_length=100)),
                ('category', models.CharField(choices=[('API', 'API Integrations'), ('CHART', 'Charts'), ('PAG', 'Pagination Templates'), ('DEVOPS', 'Devops Workings'), ('WEB3', 'Blockchains Web3')], help_text='Category of the documentation', max_length=50)),
                ('version', models.CharField(blank=True, help_text='Version of the documentation', max_length=50, null=True)),
                ('content', models.TextField(blank=True, help_text='Content of the documentation', null=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags of the documentation', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time of creation')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time of last update')),
            ],
            options={
                'verbose_name': 'Documentation',
                'verbose_name_plural': 'Documentations',
                'ordering': ['-updated_at'],
            },
        ),
    ]
