# Generated by Django 5.1.4 on 2024-12-25 20:21

import django_quill.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentation',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the documentation', null=True),
        ),
        migrations.AlterField(
            model_name='documentation',
            name='content',
            field=django_quill.fields.QuillField(blank=True, help_text='Content of the documentation', null=True),
        ),
    ]
