# Generated by Django 5.1.4 on 2024-12-25 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_documentation_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentation',
            name='content',
            field=models.TextField(blank=True, help_text='Content of the documentation', null=True),
        ),
    ]
